server:
  port: 8083

spring:
  application:
    name: chat-service
  cloud:
    nacos:
      server-addr: ipv6.maretu.top:8848
      username: nacos
      password: maretu
  config:
    import:
      - "nacos:shared-log.yaml?group=DEFAULT_GROUP&refresh=true"
      - "nacos:shared-jdbc.yaml?group=DEFAULT_GROUP&refresh=true"
      - "nacos:shared-redis.yaml?group=DEFAULT_GROUP&refresh=true"
  ai:
    openai:
      api-key: "ms-24b8c1e7-507b-409c-992f-79c7cf3523f7"
      base-url: "https://api-inference.modelscope.cn"
      chat:
        options:
          model: "deepseek-ai/DeepSeek-V3.2"
    ollama:
      base-url: http://ipv6.maretu.top:11434
      chat:
        model: deepseek-r1:7b

maretu:
  mysql:
    host: ipv6.maretu.top
    port: 3306
    database: chat_service
    username: root
    password: maretu
  redis:
    host: ipv6.maretu.top
    port: 6379
    password: maretu
    db: 0