server:
  port: 8083

spring:
  application:
    name: chat-service
  cloud:
    nacos:
      server-addr: ipv6.maretu.top:8848
      username: nacos
      password: maretu
  config:
    import:
      - "nacos:shared-log.yaml?group=DEFAULT_GROUP&refresh=true"
      - "nacos:shared-jdbc.yaml?group=DEFAULT_GROUP&refresh=true"
      - "nacos:shared-redis.yaml?group=DEFAULT_GROUP&refresh=true"
  ai:
    openai:
      api-key: "ms-2cc7452c-4482-4a2f-9788-c692b8811aaf"
      base-url: "https://api-inference.modelscope.cn"
      chat:
        options:
          model: "deepseek-ai/DeepSeek-V3.2"
      embedding:
        options:
          model: "Qwen/Qwen3-Embedding-8B"
          encoding-format: float
          dimensions: 1024
    ollama:
      base-url: http://ipv6.maretu.top:11434
      chat:
        model: deepseek-r1:7b

maretu:
  mysql:
    host: ipv6.maretu.top
    port: 3306
    database: chat_service
    username: root
    password: maretu
  redis:
    host: ipv6.maretu.top
    port: 6379
    password: maretu
    db: 0