server:
  port: 8081

spring:
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: ${DOCKER_SERVER_ADDR:ipv6.maretu.top}:8848
      username: nacos
      password: maretu
  config:
    import:
      - "nacos:shared-log.yaml?group=DEFAULT_GROUP&refresh=true"
      - "nacos:shared-thread.yaml?group=DEFAULT_GROUP&refresh=true"
      - "nacos:shared-jdbc.yaml?group=DEFAULT_GROUP&refresh=true"
      - "nacos:shared-redis.yaml?group=DEFAULT_GROUP&refresh=true"
      - "nacos:email-config.yaml?group=DEFAULT_GROUP&refresh=true"

maretu:
  mysql:
    host: ${DOCKER_SERVER_ADDR:ipv6.maretu.top}
    port: 3306
    database: user_service
    username: root
    password: maretu
  redis:
    host: ${DOCKER_SERVER_ADDR:ipv6.maretu.top}
    port: 6379
    password: maretu
    db: 0