server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
    nacos:
      server-addr: ipv6.maretu.top:8848
      username: nacos
      password: maretu
  config:
    import:
      - "nacos:gateway-routes.yaml?group=DEFAULT_GROUP&refresh=true"

maretu:
  auth:
    excludePaths:
      - /users/**
      - /chat/**